Task 1: 
 
  1. 
 
Write a function to compute 5/0 and use try/except to catch the exceptions. 
 
 

In [1]:
# Divide by zero
try:
    x = 5 / 0
except:
    print("Error dividing by zero")

Error dividing by zero


In [4]:
import sys

randomList = [3,5]

for i in randomList:
    try:
        print("The entry is", i)
        r = i/0
        break
    except:
        print("Oops!,error occured.")
 


The entry is 3
Oops!,error occured.
The entry is 5
Oops!,error occured.


2. 
 
Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"]. 
 
Hint: Subject,Verb and Object should be declared in the program as shown below. 
 
subjects=["Americans ","Indians"] verbs=["play","watch"] objects=["Baseball","Cricket"] 

Output should come as below: 
 
Americans  play Baseball. Americans  play Cricket. Americans  watch Baseball. Americans  watch Cricket. Indians play Baseball. Indians play Cricket. Indians watch Baseball. Indians watch Cricket. 
 

In [35]:
subject=["Americans", "Indians"]
verb=["Play", "watch"]
obj=["Baseball","cricket"]

In [36]:
# Use list comprehension instead of looping over each of the predicates
sentence_list = [(sub+" "+ vb + " " + ob) for sub in subject for vb in verb for ob in obj]
for sentence in sentence_list:
 print (sentence)

Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


Task 2:  
 
 
1.  
 
Write a function so that the columns of the output matrix are powers of the input vector.  
The order of the powers is determined by the increasing boolean argument. Specifically, when              increasing is False, the i-th output column is the input vector raised element-wise to the power                of N - i - 1.  
 
HINT: Such a matrix with a geometric progression in each row is named for Alexandre               Theophile Vandermonde. 
 
 

In [38]:
import numpy as np


In [44]:

def create_matrix(inputv,number,increasing=False):
    if not increasing:
        outputV=np.array([x**(number-i-1) for x in inputv for i in range(number)]).reshape(inputv.size,number)
    elif increasing:
        outputV=np.array([x**(i) for x in inputv for i in range(number)]).reshape(inputv.size,number)
        
    return outputV


inputarray = np.array([1,2,3,4,5])
no_columns=3

output_descending = create_matrix(inputarray,no_columns,False)

output_ascending =create_matrix(inputarray,no_columns,True)

print("The input array is:",inputarray,"\n")
print("Number of columns in output matrix should be:",no_columns,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",output_descending,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",output_ascending,"\n")
print("Output")


The input array is: [1 2 3 4 5] 

Number of columns in output matrix should be: 3 

Vander matrix of the input array in decreasing order of powers:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

Vander matrix of the input array in increasing order of powers:

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 

Output
